config/routes.rb
Rails.application.routes.draw do
  
  ################## DOCUMENTS  ##########################
  get "documents", to:'document#index'


  ################## MINI PROGRAMS  ##########################
  get 'min-programs', to:"miniprogram#index"


   ################## LEARN POD  ##########################
  get "new-article", to:"articles#new"
  get "articles", to:"articles#index"
  resources :articles, except: %i[:new, :index]

  ################## COURSES  ##########################
  get "new-course", to:"courses#new"
  resources :courses, except:[:new]

  
  ################## MATERIALS  ##########################
  get "new-material", to:"materials#new"
  resources :materials, except:[:new]
  
  ################## LEVELS  ##########################
  get "new-level", to:"levels#new"
  resources :levels, except:[:new]
  
  ################## DASHBOARD  ##########################
  get "dashboard", to:'dashboard#index'
  get "espace-school", to:'dashboard#school'
  get "espace-teacher", to:'dashboard#teacher'

  ################## USERS  ##########################
  devise_scope :user do
    get 'profil', to: 'devise/registrations#edit'
    get 'student-sign-in', to: 'devise/sessions#new'
    get 'student-sign-up', to: 'devise/registrations#new', as: "new_user_registration"
    delete 'deconnecter',  to: "devise/sessions#destroy", as: "destroy_user_session_path"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homepage#index"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_rich_text :content

  has_one_attached :main_image_article do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 300]
  end

  ############### VALIDATIONS ####################
  
  validates :title, length: {minimum:10, maximum:150, message:"Verifiez que le titre n'est pas trop long. la longueur du titre est limité 150 caracteres"}
  validates  :content, :user_id, :slug, presence: true
  
  ############### SLUGGED ####################
  include ItemsSlugged
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :set_material

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

     def set_material
      @materials = Material.all
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :main_image_article, :content, :hashtag_name, :slug, :user_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
<% @title= article.title %>

  
  <div class="my-5 font-bold text-2xl md:text-5xl">    
    <%= article.title %>
  </div>

  <div class="my-5 font-medium font-sans">
    <div class="my-4">
      <div class="my-2"> 
        <%= article.created_at.to_fs(:short) %>, par <%= article.user.full_name %>, <%= article.hashtag_name %>
      </div>
      <% if article.main_image_article.attached? %>
      <%#= image_tag article.main_image_article.variant(:thumb) %>
      <%= image_tag article.main_image_article %>
  <% end %>
  

    </div> 
    <div class="p-2 border bg-white">
      <%= article.content %>
    </div>
  </div>

  <% if action_name != "show" %>
    <%= link_to "Voir article", article, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% if user_signed_in?  %>
        <%= link_to 'Modifier article', edit_article_path(article), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>

    <hr class="mt-6">
  <% end %>
</div>

app/views/articles/_footer.html.erb
<hr>
<p class="">
Pour plus d'information sur Lnclass, Veiller visitez, <%= link_to 'Lnclass Education', root_path, class:"font-bold text-xl underline text-blue-600" %>
</p>


<div class="my-4">
<%= link_to 'Voir tous les articles',articles_path, class:"text-blue-600 font-bold text-xl" %>

</div>

<footer class="footer items-center p-4 bg-neutral text-neutral-content">
    <div class="items-center grid-flow-col">
        <svg width="36" height="36" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current">
            <path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path>
        </svg>
        <p>Copyright © 2023 - All right reserved</p>
    </div>
    <div class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
        <a>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
                <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
            </svg>
        </a>
        <a>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
                <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
            </svg>
        </a>
        <a>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
                <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
            </svg>
        </a>
    </div>
</footer>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "contents") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.text_field :title, 
    placeholder:"Donner le titre de l'article ...", 
    class: "article-style" %>
  </div>
  <div class="my-5">
<%= form.file_field :main_image_article,
    accept: 'image/png, image/gif, image/jpeg',
    placeholder:"Donner le titre de l'article ...", 
    class: "" %>
  </div>

  <div class="my-5">
    <%= form.rich_text_area :content,
     placeholder:"Ecrivez le contenu de l'article ...", 
class: "article-style bg-white" %>

  </div>

  <div class="w-full my-2">
    <%= form.label :Matiere %><br>
    <%= form.select :hashtag, @materials.map{|material| [material.title]}, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline my-2">
    <%= form.submit "Publiez l'Article", class: "rounded-lg py-2 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/articles/_navbar.html.erb
<div class="fixed inset-x-0 top-0 z-50 h-0.5 mt-0.5 bg-white"></div>

<div class="navbar bg-blue-600 fixed top-0 left-0 right-0 z-10">

    <div class="navbar-start">
        <div class="dropdown">
            <label tabindex="0" class="btn text-white btn-ghost lg:hidden">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16"/>
                </svg>
            </label>
            <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52 font-bold">
                <li>
                    <%= link_to 'Accueil', root_path %>
                </li>
                <li>
                    <a>Devoirs</a>
                </li>
                <li>
                    <a>Sujets Bac</a>
                </li>

                <li>
                    <a>Argent gagnez</a>
                </li>
                <div class="avatar">
                    <% member_avatar = "#{[current_user.first_name.first, current_user.last_name.first].join('')}"  %>
                    <div class="w-12 rounded-full">
                        <p class="flex h-12 w-12 rounded-full bg-gray-300 font-bold text-black mx-auto uppercase">
                            <span class="flex justify-center mx-auto py-3 "><%= member_avatar %></span>
                        </p>
                    </div>
                </div>
            </ul>
        </div>
        <%= link_to root_path, class:"btn btn-ghost font-bold normal-case text-xl md:ml-10" do %>
            <p class="block px-2 py-1 mt-2 bg-white rounded-lg  md:mt-0">
                <span class="text-white bg-blue-600 px-1">Ln</span>class
            </p>
        <% end %>

    </div>
    <div class="navbar-center hidden lg:flex">
        <ul class="menu menu-horizontal px-1 font-bold">
            <li>
                <%= link_to 'Accueil', root_path %>
            </li>
            <li>
                <%= link_to 'Nouv Cours', "new-course" %>
            </li>
            <li>
            <%= link_to 'Sujets Bac', root_path %>

            </li>

            <li>
                <%= link_to 'Invitations', "invitation" %>
            </li>

            <div class="avatar">
                <%= link_to  root_path do %>
                    <% member_avatar = "#{[current_user.first_name.first, current_user.last_name.first].join('')}"  %>
                    <div class="w-12 rounded-full">
                        <p class="flex h-12 w-12 rounded-full bg-gray-300 font-bold text-black mx-auto uppercase">
                            <span class="flex justify-center mx-auto py-3 "><%= member_avatar %></span>
                        </p>
                    </div>
                <% end %>
            </div>
            <li>
                <%= link_to "Se Déconnecter", destroy_user_session_path, method: :delete, class:"mx-3" %>
            </li>

        </ul>
    </div>
</div>

app/views/articles/edit.html.erb
<%= render "navbar" %>
<% @title="Créer l'article" %>


<div class="mx-auto md:w-2/3 w-full mt-20">
  <h1 class="font-bold text-4xl">Modifier l'article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Voir l'article", @article, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Retour aux articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/index.html.erb
<%= render "navbar" %>
<% @title="Articles" %>
<div class="w-full mt-20">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Articles</h1>
    <% if user_signed_in? %>
      <%= link_to 'Nouvel article', "new-article", class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div class="container md:mx-auto mt-20 flex flex-wrap md:flex-row flex-col">
    <% @articles.each do |article| %> 
      <div class="card w-full  md:w-1/3 bg-white shadow-xl p-2 m-2">
        <figure><%= image_tag article.main_image_article.variant(:thumb) %></figure>
        <div class="text-italic">
          <%= article.created_at.to_fs(:short) %>, par <%= article.user.full_name %>
        </div>
        <div class="card-body">
          <h2 class="card-title"><%= article.title %></h2>
          <div>
            <%= link_to article_path(article) do %>
              <%= article.title %>
            <% end %>
          </div>
          <div class="card-actions justify-end">
            <button class="bg-blue-600 hover:bg-blue-500 px-4 py-2 rounded-md font-semibold text-white">
              <%= link_to 'Lire Article', article_path(article) %>
            </button>
          </div>     
        </div>
      </div>
    <% end %> 
  </div>
</div>
  <%= render "footer" %>

app/views/articles/new.html.erb
<%= render "navbar" %>
<% @title="Créer l'article" %>
<div class="mx-auto md:w-2/3 w-full mt-20">
  <h1 class="font-bold text-4xl">Nouvel Article</h1>

  <%= render "form", article: @article %>

  <%= link_to 'Annuler', articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
<%= render "footer" %>

app/views/articles/show.html.erb
<%= render "navbar" %>
<div class="mx-auto md:w-2/3 w-full flex mt-20">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @article %>

    <% if user_signed_in? %>
      <%= link_to 'Editer article 🖋', edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

      <div class="inline-block ml-2">
        <%= button_to 'Supprimer 🗑', article_path(@article), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    <% end %>
    
  </div>
  
</div>
    <%= render "footer" %>