config/routes.rb
Rails.application.routes.draw do
  
  ################## DOCUMENTS  ##########################
  get "documents", to:'document#index'


  ################## MINI PROGRAMS  ##########################
  get 'min-programs', to:"miniprogram#index"


   ################## LEARN POD  ##########################
  get "new-article", to:"articles#new"
  get "articles", to:"articles#index"
  resources :articles, except: %i[:new, :index]

  ################## COURSES  ##########################
  get "new-course", to:"courses#new"
  resources :courses, except:[:new]

  
  ################## MATERIALS  ##########################
  get "new-material", to:"materials#new"
  resources :materials, except:[:new]
  
  ################## LEVELS  ##########################
  get "new-level", to:"levels#new"
  resources :levels, except:[:new]
  
  ################## DASHBOARD  ##########################
  get "dashboard", to:'dashboard#index'
  get "espace-school", to:'dashboard#school'
  get "espace-teacher", to:'dashboard#teacher'

  ################## USERS  ##########################
  devise_scope :user do
    get 'profil', to: 'devise/registrations#edit'
    get 'student-sign-in', to: 'devise/sessions#new'
    get 'student-sign-up', to: 'devise/registrations#new', as: "new_user_registration"
    delete 'deconnecter',  to: "devise/sessions#destroy", as: "destroy_user_session_path"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homepage#index"
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_level, only: %i[ show edit update destroy ]

  # GET /levels or /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1 or /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels or /levels.json
  def create
    @level = current_user.levels.build(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to level_url(@level), notice: "Level was successfully created." }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1 or /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to level_url(@level), notice: "Level was successfully updated." }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1 or /levels/1.json
  def destroy
    @level.destroy

    respond_to do |format|
      format.html { redirect_to levels_url, notice: "Level was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def level_params
      params.require(:level).permit(:title, :slug, :user_id)
    end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/_form.html.erb
<% if level.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(level.errors.count, "error") %>
            prohibited this level from being saved:</h2>

        <ul>
            <% level.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<%= form_with(model: level, class: "contents") do |form| %>
    <div class="flex max-w-full">
        <div class="mx-auto">
            <%= form.text_field :title, placeholder:"level name ..." %>
        </div>


        <div class="mx-auto">
            <%= form.submit "Enregistrez", class: "rounded-lg py-3 px-2 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
        </div>
    </div>
<% end %>

app/views/levels/_level.html.erb
<div id="<%= dom_id level %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= level.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Slug:</strong>
    <%= level.slug %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= level.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this level", level, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this level', edit_level_path(level), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/levels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing level</h1>

  <%= render "form", level: @level %>

  <%= link_to "Show this level", @level, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to levels", levels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/levels/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Levels</h1>
    <%= link_to 'New level', new_level_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="levels" class="min-w-full">
    <%= render @levels %>
  </div>
</div>

app/views/levels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New level</h1>

  <%= render "form", level: @level %>

  <%= link_to 'Back to levels', levels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/levels/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @level %>

    <%= link_to 'Edit this level', edit_level_path(@level), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this level', level_path(@level), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to levels', levels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>