config/routes.rb
Rails.application.routes.draw do
  
  ################## DOCUMENTS  ##########################
  get "documents", to:'document#index'


  ################## MINI PROGRAMS  ##########################
  get 'min-programs', to:"miniprogram#index"


   ################## LEARN POD  ##########################
  get "new-article", to:"articles#new"
  get "articles", to:"articles#index"
  resources :articles, except: %i[:new, :index]

  ################## COURSES  ##########################
  get "new-course", to:"courses#new"
  resources :courses, except:[:new]

  
  ################## MATERIALS  ##########################
  get "new-material", to:"materials#new"
  resources :materials, except:[:new]
  
  ################## LEVELS  ##########################
  get "new-level", to:"levels#new"
  resources :levels, except:[:new]
  
  ################## DASHBOARD  ##########################
  get "dashboard", to:'dashboard#index'
  get "espace-school", to:'dashboard#school'
  get "espace-teacher", to:'dashboard#teacher'

  ################## USERS  ##########################
  devise_scope :user do
    get 'profil', to: 'devise/registrations#edit'
    get 'student-sign-in', to: 'devise/sessions#new'
    get 'student-sign-up', to: 'devise/registrations#new', as: "new_user_registration"
    delete 'deconnecter',  to: "devise/sessions#destroy", as: "destroy_user_session_path"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homepage#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_course, only: %i[ show edit update destroy ]
   before_action :set_levels, :set_materials

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = current_user.courses.build(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    #set Level
    def set_levels
      @levels = Level.all
    end

    def set_materials
      @materials = Material.all
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :content, :level_name, :material_name, :slug, :user_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>" class="border bg-white p-2">

  <div class="my-5 font-bold text-xl">
    <%= course.title %>
  </div>


  <div class="my-5">
    <%= course.content %>
  </div>

<div class="flex justify-between">
  <p class="my-5">
    <strong class="block font-bold mb-1">Niveau:</strong>
    <%= course.level_name %>
  </p>

  <p class="my-5">
    <strong class="block font-bold mb-1">Matiere:</strong>
    <%= course.material_name %>
  </p>

  <p class="my-5">
    <strong class="block font-bold mb-1">Statut:</strong>
    <%= course.statut_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Auteur:</strong>
Prof :<%= course.user.full_name %>

  </p>
</div>
  <% if action_name != "show" %>
    <%= link_to "Show this course", course, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this course', edit_course_path(course), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/courses/_form.html.erb
  <% if course.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= form_with(model: course, class: "contents") do |form| %>

  <div class="my-5">
    <%= form.text_field :title,
      class: "block border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
      placeholder:"Titre du contenu ...", autofocus: true %>
  </div>

  <div class="my-5 bg-white p-2">
    <%= form.rich_text_area :content, 
    class: "block border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
    placeholder:"Ecrivez le contenu ..." %>
  </div>

  <!-- Items of course-->
  <div class="flex my-4">
    <div class="w-1/2">
      <%= form.label :"Niveau" %> <br>
      <%= form.select :level_name, @levels.map{|level| [level.title]}, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="w-1/2 mx-2">
      <%= form.label :Matiere %> <br>
      <%= form.select :material_name, @materials.map{|material| [material.title]}, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="">
      <%#= form.label :statut %> <br>
      <%# form.select :statut_name, @statuts.map{|statut| [statut.title]}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  </div>

  <div class="inline">
    <%= form.submit "Enregistrez", class: " py-2 px-4 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing course</h1>

  <%= render "form", course: @course %>

  <%= link_to "Show this course", @course, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/courses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Courses</h1>
    <%= link_to 'New course', new_course_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="courses" class="min-w-full">
    <%= render @courses %>
  </div>
</div>

app/views/courses/new.html.erb
<% @title="Nouveau Cours" %>
<div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">Nouveau Cours</h1>

    <%= render "form", course: @course %>

    <%= link_to 'Annuler', "dashboard", class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/courses/show.html.erb
<%= render "homepage/shared/navbar" %>

<div id="<%= dom_id @course %>" class="mx-auto md:w-2/3 w-full pt-28">
    <%#= turbo_frame_tag dom_id(@course) do %>
        <% @title=@course.title %>
        <div class="card bg-white p-2">

            <div class="font-bold text-xl md:text-2xl ">
                <%= @course.title %>
            </div>
            <div
                class="p-2">
                <!-- Course content-->
                <%= @course.content %>
            </div>
        </div>
        <%## if current_user_status =="team" || current_user_status == "teacher" %>
        <!-- Course Options-->
        <div class="flex m-4 justify-between">
            <div class="dropdown dropdown-hover">
                <label tabindex="0" class=" m-1 bg-gray-100 p-1 rounded-full">
                    <span class="badge badge-xs"></span>
                    <span class="badge badge-xs mx-0.5 "></span>
                    <span class="badge badge-xs"></span>
                </label>
                <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
                    <li>
                        <%= link_to edit_course_path(@course), class:"ln-feature-course hover:text-blue-600" do %>
                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"/>
                                </svg>
                            </span>
                            <span>Modifier</span>
                        <% end %>
                    </li>
                    <li>
                        <%= button_to course_path(@course), method: :delete, class:"text-slate-800 hover:text-blue-600 text-sm bg-white hover:bg-slate-100 border border-slate-200 rounded-r-lg font-medium px-4 py-2 inline-flex space-x-1 items-center" do %>
                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"/>
                                </svg>
                            </span>
                            <span>Supprimer</span>
                        <% end %>
                    </li>
                </ul>
            </div>
            <!-- Link Exercise Form-->
            <div class="flex">
                <%#= link_to 'Nouvel Exercice',
                    new_course_exercise_path(@course),
                    #data:{ turbo_frame:"add_exercise_form"},
                    class:"bg-blue-600 font-semibold text-white p-3" %>
            </div>
        </div>

        <!-- New Exercise Form-->
        <%#= turbo_frame_tag "add_exercise_form" %>
        


        <!-- Exercises Feed-->
        <div
            class="border bg-white m-2">
            <!-- Exercises New Form-->
            <%#= turbo_frame_tag dom_id(Exercise.new) %>
            <!-- Exercises feed-->
            <%#= render "courses/shared/exercises", course:@course %>
        </div>
        <%# end %>
    <%# end %>

</div>