config/routes.rb
Rails.application.routes.draw do
  
  ################## DOCUMENTS  ##########################
  get "documents", to:'document#index'


  ################## MINI PROGRAMS  ##########################
  get 'min-programs', to:"miniprogram#index"


   ################## LEARN POD  ##########################
  get "new-article", to:"articles#new"
  get "articles", to:"articles#index"
  resources :articles, except: %i[:new, :index]

  ################## COURSES  ##########################
  get "new-course", to:"courses#new"
  resources :courses, except:[:new]

  
  ################## MATERIALS  ##########################
  get "new-material", to:"materials#new"
  resources :materials, except:[:new]
  
  ################## LEVELS  ##########################
  get "new-level", to:"levels#new"
  resources :levels, except:[:new]
  
  ################## DASHBOARD  ##########################
  get "dashboard", to:'dashboard#index'
  get "espace-school", to:'dashboard#school'
  get "espace-teacher", to:'dashboard#teacher'

  ################## USERS  ##########################
  devise_scope :user do
    get 'profil', to: 'devise/registrations#edit'
    get 'student-sign-in', to: 'devise/sessions#new'
    get 'student-sign-up', to: 'devise/registrations#new', as: "new_user_registration"
    delete 'deconnecter',  to: "devise/sessions#destroy", as: "destroy_user_session_path"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homepage#index"
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_material, only: %i[ show edit update destroy ]

  # GET /materials or /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1 or /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials or /materials.json
  def create
    @material = current_user.materials.build(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to material_url(@material), notice: "Material was successfully created." }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1 or /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to material_url(@material), notice: "Material was successfully updated." }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1 or /materials/1.json
  def destroy
    @material.destroy

    respond_to do |format|
      format.html { redirect_to materials_url, notice: "Material was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def material_params
      params.require(:material).permit(:title, :slug, :user_id)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<% if material.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(material.errors.count, "error") %>
            prohibited this material from being saved:</h2>

        <ul>
            <% material.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<%= form_with(model: material, class: "contents flex") do |form| %>
    <div class="flex max-w-full">
        <div class="mx-auto">
            <%= form.text_field :title, placeholder:"Material name ...", autofocus: true %>
        </div>

        <div class="mx-auto">
            <%= form.submit "Enregistrez", class: "rounded-lg py-3 px-2 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
        </div>
    </div>
<% end %>

app/views/materials/_material.html.erb
<div id="<%= dom_id material %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= material.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Slug:</strong>
    <%= material.slug %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= material.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this material", material, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this material', edit_material_path(material), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/materials/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing material</h1>

  <%= render "form", material: @material %>

  <%= link_to "Show this material", @material, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to materials", materials_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/materials/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Materials</h1>
    <%= link_to 'New material', new_material_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="materials" class="min-w-full">
    <%= render @materials %>
  </div>
</div>

app/views/materials/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New material</h1>

  <%= render "form", material: @material %>

  <%= link_to 'Back to materials', materials_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/materials/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @material %>

    <%= link_to 'Edit this material', edit_material_path(@material), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this material', material_path(@material), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to materials', materials_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>